#!/bin/bash
curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-amd64
chmod +x manifest-tool
./manifest-tool push from-args --platforms linux/amd64,linux/arm/v7 --template $DOCKER_REPO:$DOCKER_TAG'-ARCHVARIANT' --target $DOCKER_REPO:$DOCKER_TAG
